name: 'File Changed Check'
description: 'Check file is chenged'
inputs:
  target:  # id of input
    description: 'target file name'
    required: true
    default: 'README.md'
  token:  # id of input
    description: 'github token'
    required: false
    default: ${{ github.token }}
outputs:
  isChanged: # id of output
    description: 'The target file is changed'
runs:
  using: 'node16'
  main: 'file-dif.js'